// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel3, 181);
    lv_obj_set_height(ui_Panel3, 62);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, -139);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x98E9F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x54AAF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -2);
    lv_obj_set_y(ui_Label3, 5);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ESP Info");

    ui_TextArea2 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea2, 150);
    lv_obj_set_height(ui_TextArea2, 44);
    lv_obj_set_x(ui_TextArea2, -2);
    lv_obj_set_y(ui_TextArea2, -46);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, flash);

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -39);
    lv_obj_set_y(ui_Label9, -5);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Flash Size");

    ui_TextArea3 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea3, 150);
    lv_obj_set_height(ui_TextArea3, 44);
    lv_obj_set_x(ui_TextArea3, -1);
    lv_obj_set_y(ui_TextArea3, 37);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, espModel);

    ui_Label5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -52);
    lv_obj_set_y(ui_Label5, -85);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Model:");

    ui_TextArea4 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea4, 150);
    lv_obj_set_height(ui_TextArea4, 44);
    lv_obj_set_x(ui_TextArea4, 1);
    lv_obj_set_y(ui_TextArea4, 118);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "0");

    ui_Label10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -27);
    lv_obj_set_y(ui_Label10, 77);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SD Card Size");

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Panel3 = NULL;
    ui_Label3 = NULL;
    ui_TextArea2 = NULL;
    ui_Label9 = NULL;
    ui_TextArea3 = NULL;
    ui_Label5 = NULL;
    ui_TextArea4 = NULL;
    ui_Label10 = NULL;

}
